### ISSUE TITLE
Strange error when lower time bound is supplied

### ISSUE THREAD

**Issue by gianm** [implydata/plyql#1]
See https://groups.google.com/forum/#!msg/imply-user-group/vBkduq04V2k/b-5atWy5BwAJ.

The query `plyql -h placeholder:8081 -q "SELECT field_name FROM datasource_name where '2015-11-30T00:00:00' <= __time limit 5"` yielded the error `There was an error getting the data: Cannot read property 'toISOString' of null`.

I *think* this is happening when only a lower time bound is supplied (but not an upper bound).

**Comment by vogievetsky** [comment]
Thanks for filing!
