### ISSUE TITLE
querySegmentSpec can't be null error for segmentMetadata query

### ISSUE THREAD

**Issue by smountain** [implydata/plyql#10]
When running some queries I noticed an error that always seems to occur for the first query segmentMetadata is sent: ``Got error in query 1: Instantiation of [simple type, class io.druid.query.metadata.metadata.SegmentMetadataQuery] value failed: querySegmentSpec can't be null (in 1092ms)``.

This seems to happen for every query I have tried (groupBy, timeseries, etc.) but the rest of the queries in the chain finish and I get output but I was curious if the failure of the first query is expected or could be causing some issues with the PlyQL/Plywood processing.

Also, I was under the impression that PlyQL/Plywood would try to process groupBy queries in a more efficient manner if possible by using topNs but in my experience so far I always see GROUP BY queries stay as groupBy queries. Could the failure of the segmentMetadata be impacting that or will  GROUP BY PlyQL queries always be processed as Druid groupBy?

I am running Druid 0.8.1 if that helps.

Query:
```
SELECT sum(value), pop, interface, description FROM datasource WHERE description REGEXP 'abc' AND pop REGEXP '(abc01)' AND '2016-02-09T17:44:20.297Z' <= __time AND __time < '2016-02-09T23:04:20.297Z' GROUP BY TIME_BUCKET(__time, PT1M, 'Etc/UTC'), pop, interface, description ORDER BY pop DESC
```

Verbose output:
```
{
  "op": "chain",
  "expression": {
    "op": "ref",
    "name": "datasource"
  },
  "actions": [
    {
      "action": "filter",
      "expression": {
        "op": "chain",
        "expression": {
          "op": "ref",
          "name": "description"
        },
        "actions": [
          {
            "action": "match",
            "regexp": "abc"
          },
          {
            "action": "and",
            "expression": {
              "op": "chain",
              "expression": {
                "op": "ref",
                "name": "pop"
              },
              "action": {
                "action": "match",
                "regexp": "(abc01)"
              }
            }
          },
          {
            "action": "and",
            "expression": {
              "op": "chain",
              "expression": {
                "op": "literal",
                "value": "2016-02-09T22:42:18.794Z"
              },
              "action": {
                "action": "lessThanOrEqual",
                "expression": {
                  "op": "ref",
                  "name": "__time"
                }
              }
            }
          },
          {
            "action": "and",
            "expression": {
              "op": "chain",
              "expression": {
                "op": "ref",
                "name": "__time"
              },
              "action": {
                "action": "lessThan",
                "expression": {
                  "op": "literal",
                  "value": "2016-02-09T22:47:18.794Z"
                }
              }
            }
          }
        ]
      }
    },
    {
      "action": "split",
      "splits": {
        "description": {
          "op": "ref",
          "name": "description"
        },
        "interface": {
          "op": "ref",
          "name": "interface"
        },
        "pop": {
          "op": "ref",
          "name": "pop"
        },
        "split0": {
          "op": "chain",
          "expression": {
            "op": "ref",
            "name": "__time"
          },
          "action": {
            "action": "timeBucket",
            "duration": "PT1M",
            "timezone": "Etc/UTC"
          }
        }
      },
      "dataName": "data"
    },
    {
      "action": "apply",
      "expression": {
        "op": "chain",
        "expression": {
          "op": "ref",
          "name": "data"
        },
        "action": {
          "action": "sum",
          "expression": {
            "op": "ref",
            "name": "value"
          }
        }
      },
      "name": "sum_value"
    },
    {
      "action": "sort",
      "expression": {
        "op": "ref",
        "name": "pop"
      },
      "direction": "descending"
    }
  ]
}
---------------------------
vvvvvvvvvvvvvvvvvvvvvvvvvv
Sending query 1:
{
  "queryType": "segmentMetadata",
  "dataSource": "datasource",
  "merge": true,
  "analysisTypes": [
    "aggregators"
  ],
  "lenientAggregatorMerge": true
}
^^^^^^^^^^^^^^^^^^^^^^^^^^
vvvvvvvvvvvvvvvvvvvvvvvvvv
Got error in query 1: Instantiation of [simple type, class io.druid.query.metadata.metadata.SegmentMetadataQuery] value failed: querySegmentSpec can't be null (in 1092ms)
^^^^^^^^^^^^^^^^^^^^^^^^^^
vvvvvvvvvvvvvvvvvvvvvvvvvv
Sending query 2:
{
  "queryType": "introspect",
  "dataSource": "datasource"
}
^^^^^^^^^^^^^^^^^^^^^^^^^^
vvvvvvvvvvvvvvvvvvvvvvvvvv
Got result from query 2: (in 13ms)
{
  "dimensions": [
    "description",
    "interface",
    "pop"
  ],
  "metrics": [
    "value"
  ]
}
^^^^^^^^^^^^^^^^^^^^^^^^^^
vvvvvvvvvvvvvvvvvvvvvvvvvv
Sending query 3:
{
  "queryType": "groupBy",
  "dataSource": "datasource",
  "intervals": [
    "2016-02-09T22:42:18.794/2016-02-09T22:47:18.794"
  ],
  "granularity": "all",
  "context": {
    "timeout": 60000
  },
  "filter": {
    "type": "and",
    "fields": [
      {
        "type": "regex",
        "dimension": "description",
        "pattern": "abc"
      },
      {
        "type": "regex",
        "dimension": "pop",
        "pattern": "(abc01)"
      }
    ]
  },
  "aggregations": [
    {
      "name": "sum_value",
      "type": "doubleSum",
      "fieldName": "value"
    }
  ],
  "dimensions": [
    {
      "type": "default",
      "dimension": "description",
      "outputName": "description"
    },
    {
      "type": "default",
      "dimension": "interface",
      "outputName": "interface"
    },
    {
      "type": "default",
      "dimension": "pop",
      "outputName": "pop"
    },
    {
      "type": "extraction",
      "dimension": "__time",
      "outputName": "split0",
      "extractionFn": {
        "type": "timeFormat",
        "format": "yyyy-MM-dd'T'HH:mm'Z",
        "timeZone": "Etc/UTC",
        "locale": "en-US"
      }
    }
  ],
  "limitSpec": {
    "type": "default",
    "limit": 500000,
    "columns": [
      {
        "dimension": "pop",
        "direction": "descending"
      }
    ]
  }
}
^^^^^^^^^^^^^^^^^^^^^^^^^^
vvvvvvvvvvvvvvvvvvvvvvvvvv
Got result from query 3: (in 52ms)
... RESULTS ...
```

Thanks for your time!

**Comment by gianm** [comment]
Hey @smountain, this is expected and is Plywood going through the process of figuring out how best to introspect your Druid datasource. Newer versions of Druid support better kinds of introspection, and those are tried first. Eventually it will find one that works and use that. Your results should still be ok.

If you update to the latest Druid then Plywood will be able to use a better form of introspection than what it chose for your Druid (although the first one it checks will still fail, as it's checking for a feature in master that is not in a release yet).

**Comment by vogievetsky** [comment]
Regarding the error:
As @gianm said, the error is expected. You will keep getting some error until you start using the (yet unreleased) Druid 0.9.0. But with every druid upgrade (0.8.2, 0.8.3) Plywood will be getting more and more info about you cluster. If the error offends you add the flag `--introspection-strategy datasource-get` to the command line. I would not recommend that though.

Regarding using topNs, Plywood does not (yet) simplify your multidimensional Group Bys into topNs. A multidimensional group by will always perform a groupBy query.

The true power of PlyQL/Plywood is in **nested** splits (group bys)

Consider the query: 

```sql
SELECT
  sum(value) AS 'Value',
  pop,
  interface
FROM datasource
WHERE 
  description REGEXP 'abc' AND
  '2016-02-09T17:44:20.297Z' <= __time AND __time < '2016-02-09T23:04:20.297Z'
GROUP BY
  pop,
  interface
ORDER BY pop DESC
```

PlyQL can do that with a group by, but an alternative query you could do (if it makes sense for your use case) is:

```sql
SELECT
  sum(value) AS 'ValueTotal',
  pop,
  (SELECT interface, sum(value) AS 'Value'
   GROUP BY interface
   ORDER BY Value DESC LIMIT 10) AS Interfaces
FROM datasource
WHERE 
  description REGEXP 'abc' AND
  '2016-02-09T17:44:20.297Z' <= __time AND __time < '2016-02-09T23:04:20.297Z'
GROUP BY
  pop,
ORDER BY pop DESC
LIMIT 100
```

This will give you the list of the top 10 interfaces by sum(value) **for each** of the top 100 pops by pop (whatever that is).

If those are high cardinality dimensions this query might me dramatically faster than the group by. It also gives you precise control on the sort and limit within each nested sub grouping.

In [Pivot](https://github.com/implydata/pivot) this kind of query is used to render the nested table:

![image](https://cloud.githubusercontent.com/assets/177816/12940251/3620ef68-cf7c-11e5-84f7-dba9ca8aba86.png)

Here is the visual result of a City nested by Page on a wikipedia edits data source, note that there are so many pages on Wikipedia that making a straight up group by query is sub optimal.

This is not limited to topNs, say you wanted to get a time breakdown (timeseries for each interface) you could do:

```sql
SELECT
  interface,
  sum(value) AS 'ValueTotal',
  (SELECT TIME_BUCKET(__time, PT1M, 'Etc/UTC') as 'Minute', sum(value) AS 'Value'
   GROUP BY 1 -- this is a shortcut for grouping on the first column so I do not have to type it out twice
   ORDER BY `Minute`) AS Minutes
FROM datasource
WHERE 
  '2016-02-09T17:44:20.297Z' <= __time AND __time < '2016-02-09T23:04:20.297Z'
GROUP BY
  interface,
ORDER BY interface DESC
LIMIT 100
```

I advice you to try these queries and see what they do with the verbose mode :-)

**Comment by smountain** [comment]
Understood, that makes more sense now. Thanks @gianm and @vogievetsky for the explanation. I am writing queries using the nested split approach and I am seeing multiple concurrent executions of timeseries queries, so that looks good.

I will update Druid to 0.9.0 when available as well. This issue can be closed. Thanks again!

**Comment by vogievetsky** [comment]
Just realized that I forgot to close this issue :-)
