### ISSUE TITLE
Query through socks5 (+ possibly other) proxies

### ISSUE THREAD

**Issue by gianm** [implydata/plyql#11]
An option similar to curl's `--socks5-hostname` or `--proxy` (with socks5:// protocol) would be super useful for my environment. for reference, https://curl.haxx.se/docs/manpage.html

**Comment by vogievetsky** [comment]
Interesting

**Comment by davidagee** [comment]
Please note that this project is now deprecated. Please see the [Druid SQL docs](http://druid.incubator.apache.org/docs/latest/querying/sql) for information on using SQL syntax with Druid.
