### ISSUE TITLE
Parse reduced-precision ISO8601 dates and times

### ISSUE THREAD

**Issue by gianm** [implydata/plyql#12]
ISO8601 allows reduced precision dates and times, which Druid does understand and are also sometimes useful for typing out a query with fewer keystrokes. It seems that plyql supports some of these but not all of them. Some examples,

2016
2016-01
2016-01-01T00
2016-01-01T00:00

[these all resolve to the same instant: 2016-01-01T00:00:00.000Z]

**Comment by vogievetsky** [comment]
`2016-01-01T00` and `2016-01-01T00:00` should work now in 0.6.1

**Comment by vogievetsky** [comment]
All done in 0.6.16.

```
$ plyql -h 192.168.99.100 -i P1Y -q 'SELECT COUNT(*) FROM wikipedia WHERE "2015" < __time AND __time < "2015-09-12T12"'
[
  {
    "COUNT": 163972
  }
]
$ plyql -h 192.168.99.100 -i P1Y -tz America/Los_Angeles -q 'SELECT COUNT(*) FROM wikipedia WHERE "2015" < __time AND __time < "2015-09-12T12"'
[
  {
    "COUNT": 303190
  }
]
```

There is also a cool --timezone attribute (default Etc/UTC) for parsing dates that have no timezone (like Z or +00:00) attached to them like `"2015-09-12T12"`
