### ISSUE TITLE
Special character escaping

### ISSUE THREAD

**Issue by l15k4** [implydata/plyql#15]
Hey,

I have some dimensions with `:` character which is a special char. But I can't find a way to escape it. So I currently cannot `SELECT` it or `GROUP BY` it... But there must be a way since Pivot can handle it via plywood... Do you know how it can be done ?

**Comment by vogievetsky** [comment]
Can you post the query that you are trying to do please? PlyQL (like MySQL) uses back ticks for column / variable name escapes.

```
plyql -h 192.168.99.100 -v -q 'SELECT `hello:world` FROM wikipedia GROUP BY 1'
```

Works as expected for me.

Closing this issue. Please reopen it if you find a specific query that fails to parse. (and please include the query)

**Comment by l15k4** [comment]
Yeah, that works, I didn't switch double qoutes to single qoutes, thanks !
