### ISSUE TITLE
long multidimension groupBy response time

### ISSUE THREAD

**Issue by smountain** [implydata/plyql#16]
Hello, 

We are trying to execute the following query as a multidimensional groupBy, which seems to result in a long amount of processing time on PlyQL/Plywood end vs the Druid end for approximately 70,000 results from Druid. Druid returns in about 10 seconds, but PlyQL/Plywood seems to be processing for 20-30 seconds. 

We see good speeds from single dimension groupBys, but I was wondering if there might be an issue that is causing the results to take longer for this particular multidimension group by query.

Thanks!

PlyQL Query:
SELECT sum(value), pop, interface, hostname, description FROM datasource WHERE pop REGEXP 'abc01' AND description REGEXP '(a|b|c):(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16):' AND measurement = 'input' AND '2016-03-12T20:16:09.956Z' <= __time AND __time < '2016-03-14T20:16:09.958Z' GROUP BY TIME_BUCKET(__time, PT1M, 'Etc/UTC'), pop, interface, hostname, description ORDER BY interface ASC

Parsed query as the following plywood expression (as JSON):
{
  "op": "chain",
  "expression": {
    "op": "ref",
    "name": "datasource"
  },
  "actions": [
    {
      "action": "filter",
      "expression": {
        "op": "chain",
        "expression": {
          "op": "ref",
          "name": "pop"
        },
        "actions": [
          {
            "action": "match",
            "regexp": "abc01"
          },
          {
            "action": "and",
            "expression": {
              "op": "chain",
              "expression": {
                "op": "ref",
                "name": "description"
              },
              "action": {
                "action": "match",
                "regexp": "(a|b|c):(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16):"
              }
            }
          },
          {
            "action": "and",
            "expression": {
              "op": "chain",
              "expression": {
                "op": "ref",
                "name": "measurement"
              },
              "action": {
                "action": "is",
                "expression": {
                  "op": "literal",
                  "value": "input"
                }
              }
            }
          },
          {
            "action": "and",
            "expression": {
              "op": "chain",
              "expression": {
                "op": "literal",
                "value": "2016-03-12T20:16:09.956Z"
              },
              "action": {
                "action": "lessThanOrEqual",
                "expression": {
                  "op": "ref",
                  "name": "__time"
                }
              }
            }
          },
          {
            "action": "and",
            "expression": {
              "op": "chain",
              "expression": {
                "op": "ref",
                "name": "__time"
              },
              "action": {
                "action": "lessThan",
                "expression": {
                  "op": "literal",
                  "value": "2016-03-14T20:16:09.958Z"
                }
              }
            }
          }
        ]
      }
    },
    {
      "action": "split",
      "splits": {
        "description": {
          "op": "ref",
          "name": "description"
        },
        "hostname": {
          "op": "ref",
          "name": "hostname"
        },
        "interface": {
          "op": "ref",
          "name": "interface"
        },
        "pop": {
          "op": "ref",
          "name": "pop"
        },
        "split0": {
          "op": "chain",
          "expression": {
            "op": "ref",
            "name": "__time"
          },
          "action": {
            "action": "timeBucket",
            "duration": "PT1M",
            "timezone": "Etc/UTC"
          }
        }
      },
      "dataName": "data"
    },
    {
      "action": "apply",
      "expression": {
        "op": "chain",
        "expression": {
          "op": "ref",
          "name": "data"
        },
        "action": {
          "action": "sum",
          "expression": {
            "op": "ref",
            "name": "value"
          }
        }
      },
      "name": "sum_value"
    },
    {
      "action": "sort",
      "expression": {
        "op": "ref",
        "name": "interface"
      },
      "direction": "ascending"
    }
  ]
}
---------------------------
vvvvvvvvvvvvvvvvvvvvvvvvvv
Sending query 1:
{
  "queryType": "segmentMetadata",
  "dataSource": "datasource",
  "merge": true,
  "analysisTypes": [
    "aggregators"
  ],
  "lenientAggregatorMerge": true
}
^^^^^^^^^^^^^^^^^^^^^^^^^^
vvvvvvvvvvvvvvvvvvvvvvvvvv
Got error in query 1: Instantiation of [simple type, class io.druid.query.metadata.metadata.SegmentMetadataQuery] value failed: querySegmentSpec can't be null (in 1073ms)
^^^^^^^^^^^^^^^^^^^^^^^^^^
vvvvvvvvvvvvvvvvvvvvvvvvvv
Sending query 2:
{
  "queryType": "introspect",
  "dataSource": "datasource"
}
^^^^^^^^^^^^^^^^^^^^^^^^^^
vvvvvvvvvvvvvvvvvvvvvvvvvv
Got result from query 2: (in 18ms)
{
  "dimensions": [
    "description",
    "hostname",
    "pop",
    "interface",
    "measurement",
  ],
  "metrics": [
    "value"
  ]
}
^^^^^^^^^^^^^^^^^^^^^^^^^^
vvvvvvvvvvvvvvvvvvvvvvvvvv
Sending query 3:
{
  "queryType": "groupBy",
  "dataSource": "datasource",
  "intervals": [
    "2016-03-12T20:16:09.956/2016-03-14T20:16:09.958"
  ],
  "granularity": "all",
  "context": {
    "timeout": 60000
  },
  "filter": {
    "type": "and",
    "fields": [
      {
        "type": "regex",
        "dimension": "pop",
        "pattern": "abc01"
      },
      {
        "type": "regex",
        "dimension": "description",
        "pattern": "(a|b|c):(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16):"
      },
      {
        "type": "selector",
        "dimension": "measurement",
        "value": "input"
      }
    ]
  },
  "aggregations": [
    {
      "name": "sum_value",
      "type": "doubleSum",
      "fieldName": "value"
    }
  ],
  "dimensions": [
    {
      "type": "default",
      "dimension": "description",
      "outputName": "description"
    },
    {
      "type": "default",
      "dimension": "hostname",
      "outputName": "hostname"
    },
    {
      "type": "default",
      "dimension": "interface",
      "outputName": "interface"
    },
    {
      "type": "default",
      "dimension": "pop",
      "outputName": "pop"
    },
    {
      "type": "extraction",
      "dimension": "__time",
      "outputName": "split0",
      "extractionFn": {
        "type": "timeFormat",
        "format": "yyyy-MM-dd'T'HH:mm'Z",
        "timeZone": "Etc/UTC",
        "locale": "en-US"
      }
    }
  ],
  "limitSpec": {
    "type": "default",
    "limit": 500000,
    "columns": [
      {
        "dimension": "interface",
        "direction": "ascending"
      }
    ]
  }
}
^^^^^^^^^^^^^^^^^^^^^^^^^^
vvvvvvvvvvvvvvvvvvvvvvvvvv
Got result from query 3: (in 9390ms)
About 70,000 results

Got result from from PlyQL about 20-30 seconds later

**Comment by vogievetsky** [comment]
What version of PlyQL is that on? Could you confirm that this is also the case in the latest version? (I suspect that it is). Recently PlyQL parsing speed was greatly improved but it looks here like the issue is with post-processing the results.

**Comment by Jhors2** [comment]
Hey @vogievetsky we upgraded to 0.6.12 to be sure, query return time is about the same as before.  As you said, it appears to be with the post processing of the results.

**Comment by vogievetsky** [comment]
Yeah there is a bunch of work that Plywood is doing to that result that is not needed since you are not doing any nested splits. I can not reproduce a case on my end where the %time spent post processing is as large as yours but it is very sizable. I will look into optimizing and get back to you.

**Comment by vogievetsky** [comment]
Just shipped 0.6.16 that is optimized to skip a lot of unnecessary work (in your use case). My bench marks show quite an improvement. Can you try that query again on 0.6.16?

**Comment by smountain** [comment]
Thank @vogievetsky, we upgraded to 0.6.16 and we are seeing greatly improved processing speeds. 
We'll report any additional processing speed issues if they come up as we have a variety of queries being executed, but so far it looks good.

Thanks!

**Comment by vogievetsky** [comment]
Great! Thanks for updating.
