### ISSUE TITLE
meaningful error should be returned when trying to select aggregate and non-aggregate column without explicit group by

### ISSUE THREAD

**Issue by evasomething** [implydata/plyql#18]
Version: plyql version 0.6.16 (plywood version 0.9.22)
Query: plyql -h 192.168.60.100:8082 -a select -i P1Y -q "SELECT page, COUNT() FROM wikipedia;"
Error: There was an error getting the data: could not resolve $page

**Comment by davidagee** [comment]
Please note that this project is now deprecated. Please see the [Druid SQL docs](http://druid.incubator.apache.org/docs/latest/querying/sql) for information on using SQL syntax with Druid.
