### ISSUE TITLE
Plyql lacks Bound Filters on string Dimensions

### ISSUE THREAD

**Issue by Jhors2** [implydata/plyql#20]
We have a use case where we want plyql to transform a greater than AND less than or equal to operation to a bound query against a string type dimension in druid:

Data Example:
```
srcAddr = aaaa, value = 1, timestamp = 2016-04-09T21:55:45.284Z
srcAddr = ffff, value = 2, timestamp = 2016-04-09T21:55:45.284Z
```
Query Example:
```
SELECT COUNT(*) FROM flowdata WHERE '2016-04-09T21:55:45.284Z' <= __time AND __time < '2016-04-19T21:55:45.284Z' AND srcAddr >= 'aaaa' AND srcAddr <= 'ffff'
```

Specifically we would like the above to turn into the following filter:
```
{
    "type": "bound",
    "dimension": "srcAddr",
    "lower": "aaaa",
    "upper": "ffff" 
}
```

**Comment by vogievetsky** [comment]
Yep it would be cool to support comparisons on STRINGs right now this is not supported in Plywood so this is not a straight forward improve-the-plyql parser task.

I will update with progress.

**Comment by evasomething** [comment]
This is added in the new version of PlyQL (0.8.9)
