### ISSUE TITLE
Concurrently run queries when nested selects are used

### ISSUE THREAD

**Issue by Jhors2** [implydata/plyql#21]
In the following query:
```
"SELECT interface_in, sum(bps) as 'bps_total', 
(SELECT TIME_BUCKET(__time, PT1M, 'Etc/UTC') as 'Time', 
sum(bps) AS 'Value' GROUP BY 1) AS TIME_RANGE 
FROM flows WHERE '2016-04-20T20:53:00.000Z'
 <= __time AND __time < '2016-04-20T21:51:48.750Z' 
GROUP BY interface_in ORDER BY bps_total desc limit 10"
```
Plyql first runs a top-N query with a limit of 10 to get the highest interface_in bps, it then runs a single time-series query for each result returned from the first.  I propose that when the above case is caught all queries should be run concurrently then the results are blocked on a wait group. 

Ultimately more concurrent connections to the broker will occur, however in our above case all queries return in a single second.  Because of the lack of concurrency regardless of how large of a time window we use, 10 seconds is the minimum query time.

**Comment by vogievetsky** [comment]
Are you sure that is is running "single time-series query for each result returned from the first" and not **two** time-series query for each result returned from the first concurrently? 😜 

There is a command line option: 

```
 -c,  --concurrent   the limit of concurrent queries that could be made simultaneously, 0 = unlimited, (default: 2)
```

which is 2 by default. It appears to work for me.

Try issuing your query with `-c 1000000`

![Dr evil](https://i.ytimg.com/vi/cmQLnBtDjbw/maxresdefault.jpg)

**Comment by Jhors2** [comment]
I was definitely missing the above, the query now runs concurrently.
