### ISSUE TITLE
Make the first status native druid query optional

### ISSUE THREAD

**Issue by l15k4** [implydata/plyql#26]
Hey,

trying to improving the performance I've notice that plyql is always issuing a status request : 
```
Sending query 1:
{
  "queryType": "status"
}
^^^^^^^^^^^^^^^^^^^^^^^^^^
vvvvvvvvvvvvvvvvvvvvvvvvvv
Got result from query 1: (in 101ms)
```

Don't know why but it takes a lot of time, even within ec2 network... Considering we need to handle 40 regs/s then basically only this time causes that we can hardly ever make it unless we'd scale it very much both horizontally and vertically ... 

I deployed plyql-server to the same node where Broker is so I'm minimizing this time but it would be essential for remote plyql clients

**Comment by vogievetsky** [comment]
Hi, PlyQL will make that query once per startup so it should not be a problem if you are running in a server mode. Also the reason it is making that query is to find out the Druid version (so it knows what query expressions are supported). You can have plyql not make that query if you explicitly tell it what druid version you have with `--druid-version 0.9.0` (or whatever you version is)
