### ISSUE TITLE
Basic auth not working

### ISSUE THREAD

**Issue by l15k4** [implydata/plyql#27]
Hey,

is this supposed to work? 

```
$ plyql --allow eternity --host user:psswd@hostname:80 -q "SELECT COUNT(*) FROM gwiq"
There was an error getting the data: getaddrinfo ENOTFOUND gwi gwi:8080
```

Or basic auth is not implemented in `plyql` ?

I would use curl to reach the `plyql-server`, but I have troubles with putting a request together if it contains backticks and quotes : 

```
curl -X POST 'http://user:psswd@hostname/plyql' \
  -H 'content-type: application/json' \
  -d '{
  "sql": "SELECT COUNT(DISTINCT id) as id FROM foo WHERE (cid = 'c0069' AND \`c-geo:c3\` = 'dom')"
}'
```

**Comment by vogievetsky** [comment]
Hi I am confused what you expect  `plyql --allow eternity --host user:psswd@hostname:80 -q "SELECT COUNT(*) FROM gwiq"` to do.

Host is your broker host, so are you trying to connect to it with basic auth? Does Druid support that? (If so I was not aware, please link me to the docs)

**Comment by l15k4** [comment]
Hi, Druid doesn't support that, I just have nginx with basic auth in front of Broker so : 
```
plyql -> nginx -> broker
```
I can access plyql-server behind nginx using `curl` but I cannot use `plyql` anymore because if it...

**Comment by vogievetsky** [comment]
Ah cool, yeah PlyQL would not support that but it could :-)

**Comment by davidagee** [comment]
Please note that this project is now deprecated. Please see the [Druid SQL docs](http://druid.incubator.apache.org/docs/latest/querying/sql) for information on using SQL syntax with Druid.
