### ISSUE TITLE
Time-less-than-or-equal-to operator pulls in too many milliseconds

### ISSUE THREAD

**Issue by gianm** [implydata/plyql#3]
A time filter like `'2016-01-08T20:53:37.000Z' <= __time AND __time <= '2016-01-08T20:53:38.000Z'` should resolve to intervals = `2016-01-08T20:53:37.000Z/2016-01-08T20:53:38.001Z` but it actually resolves to `2016-01-08T20:53:37/2016-01-08T20:53:39`.

**Comment by vogievetsky** [comment]
man, what ever happens on exact milliseconds :-p
