### ISSUE TITLE
MySQL gateway not allowing to SHOW FULL TABLES

### ISSUE THREAD

**Issue by TheMP** [implydata/plyql#35]
Hi, one the libraries I use tried to issue a following query:

SHOW FULL TABLES FROM \`plyql1\` LIKE '%'. 

This clearly is not working for two reasons: 
1. SHOW FULL TABLES is currently unsupported.
2. druid tables are not really in plyql1 database (it is acting weird), which can be verified by: the following:

```
mysql> use plyql1;
Database changed
mysql> select DATABASE();
+------------+
| DATABASE() |
+------------+
| plyql1     |
+------------+

mysql> show tables;
+--------------------------+
| Tables_in_database       |
+--------------------------+
| COLUMNS                  |
| SCHEMATA                 |
| TABLES                   |
| cc-causecode-dev         |
| new-gi-test              |
| nicer-gi-no-imsi-staging |
| nicer-gi-staging         |
| nicer-mme-staging        |
| wikipedia                |
+--------------------------+


mysql> describe plyql1;
Empty set (0.00 sec)
```

**Comment by vogievetsky** [comment]
`SHOW FULL TABLES` was fixed yesterday: https://github.com/implydata/plyql/issues/34

As for `describe plyql1;` will look into it.

**Comment by vogievetsky** [comment]
Wait `plyql1` pretends to be a database. `describe plyql1;` should not work because there is no table called `plyql1` ideally it should return an error.

**Comment by TheMP** [comment]
Oops you are right, describe should return an error. I had a brainfart since it shouldn't even work ;)
