### ISSUE TITLE
Add support for SHOW CREATE TABLE 

### ISSUE THREAD

**Issue by TheMP** [implydata/plyql#36]
Apparently one of the drivers I use requires this command to be working:

> Query:
> SHOW CREATE TABLE `plyql1`.`test`
> If you believe this query should work please create an issue on PlyQL and include this section
> Issue url: https://github.com/implydata/plyql/issues

**Comment by Digma** [comment]
I encountered this same problem with Metabase. It seems the clojure jdbc driver requires this command.

**Comment by davidagee** [comment]
Please note that this project is now deprecated. Please see the [Druid SQL docs](http://druid.incubator.apache.org/docs/latest/querying/sql) for information on using SQL syntax with Druid.
