### ISSUE TITLE
mysql gateway does not see new incoming data to druid

### ISSUE THREAD

**Issue by tsvgmi** [implydata/plyql#38]
The query from mysql client only returns data in druid up to the time mysql gateway started.  Any data from that point on is not seen 

plyql -h hostname:80 -i P2Y --experimental-mysql-gateway 3307 --skip-cache

from mysql

select * from table order by __time desc limit 10;

This only return a different set whenever the plyql is restarted.

**Comment by benvogan** [comment]
I would like to set reasonable expectations for this project as I understand that the MySQL gateway is an alpha feature and only a part of what plyql does.  How important is the MySQL gateway to Imply and should I expect a fix for this to be coming in the short term?  I need to decide whether to allocate resources to either work on fixes to it, or move in a different direction.  Thanks.

**Comment by vogievetsky** [comment]
Hi when you start plyql with -i P2Y it is the same as saying -i P2Y/<current date> i.e. explicitly constrain the query to the last 2 years from now. You can omit -i P2Y or set it to -i P2Y/2020-01-01 or maybe the year 3000
