### ISSUE TITLE
Support for LOCATE() function?

### ISSUE THREAD

**Issue by hrzn** [implydata/plyql#39]
Hello,

Thanks for PlyQL, it's a really cool tool to use with Druid :)

I noticed that when Tableau (9.3.1) is used with MySQL, it generates queries of the following form for filtering:
`WHERE (LOCATE('xyz', column)) > 0)`
which are apparently not supported in PlyQL:
`ERROR 1064 (_____): SQL parse error: Expected "*", "+", "-", ".", "/", "AND", "BETWEEN", "CONTAINS", "IN", "IS", "LIKE", "NOT", "OR", "REGEXP", ) or Comparison but "("   ##found`.

It would be nice as a feature to support such queries as it would enable filtering with Tableau.

**Comment by vogievetsky** [comment]
Totally make sense. Will add.

**Comment by evasomething** [comment]
This is added in the new version of PlyQL (0.8.9)
