### ISSUE TITLE
Time-greater-than operator pulls in not enough milliseconds

### ISSUE THREAD

**Issue by gianm** [implydata/plyql#4]
A time filter like `'2016-01-08T20:53:37.000Z' < __time AND __time < '2016-01-08T20:53:38.000Z'` should resolve to intervals = `2016-01-08T20:53:37.001Z/2016-01-08T20:53:38.000Z` but it actually resolves to `2016-01-08T20:53:38/2016-01-08T20:53:38`.

**Comment by vogievetsky** [comment]
I believe that reality is divided into seconds any further devision is heresy. Some things, like the atom, simply can not be split further.
