### ISSUE TITLE
Plyql : Query case sensitive 

### ISSUE THREAD

**Issue by rajitha703** [implydata/plyql#42]
Hi @vogievetsky  ,

Noticed that fields and table names in plyql query needs to be case sensitive else the query will fail like this : 
mysql> select page , sum( count ) from wikiticker   where '2015-09-12T00:00:00' <= __time  and  __time < '2015-09-13T00:00:00'  group by page limit 1;
| page            | sum( count ) |
+-----------------+--------------+
| (1510) Charlois |            1 |

mysql> select PAGE , sum( count ) from wikiticker   where '2015-09-12T00:00:00' <= __time  and  __time < '2015-09-13T00:00:00' group by page limit 1;
ERROR 1337 (_____):something broke
----------------------------------------------------------------------------------------------------------------------------------
As you can see, PAGE in upper case doesn't work as the schema is in lower case on Druid. Can this be looked into.  I have seen that most of the sql languages are case insensitive which is not the case here.

**Comment by evasomething** [comment]
Hi this is fixed in version 0.8.13!

**Comment by rajitha703** [comment]
@evasomething Thanks very much.
