### ISSUE TITLE
plyql not supporting FROM_UNIXTIME

### ISSUE THREAD

**Issue by fedecasanova72** [implydata/plyql#43]
Hi there!

I'm trying to do a WHERE __time BETWEEN FROM_UNIXTIME() AND FROM_UNIXTIME() query, but plyql is complaining.

Are you planning to add it? Is there a workaround to work with UNIX timestamps?

Thanks!

**Comment by vogievetsky** [comment]
It will be added.

**Comment by vogievetsky** [comment]
Added as part of plyql 0.8.8

try:

`plyql -h 192.168.99.100 -o json -q 'SELECT FROM_UNIXTIME(1447430881) AS T'`
