### ISSUE TITLE
PlyQL through JDBC doesn't return updated data

### ISSUE THREAD

**Issue by fedecasanova72** [implydata/plyql#44]
If I'm not doing anything incorrectly, here's what happens:

I'm ingesting 80 million rows to Druid through Kafka. In the meantime, I want to start querying them.

Let's just check how many rows are already indexed.

`plyql -h IPADDRESS -q 'SELECT count(*) as cnt FROM content_log'`

Result: (correct).

```
┌─────────┐
│ cnt     │
├─────────┤
│ 3706116 │
└─────────┘
```
Previously I started the PlyQL MySQL gateway.

`plyql -h your.druid.broker:8082 -i P2Y --experimental-mysql-gateway 3307` 

And if I run the same query in a Java app with JDBC, the result is: 999756. And it hasn't change since the gatewat start.

Do you know this problem?

**Comment by fedecasanova72** [comment]
#38 

Just found out there's already an issue opened about this.

**Comment by vogievetsky** [comment]
Hi when you start plyql with `-i P2Y` it is the same as saying `-i P2Y/<current date>` i.e. explicitly constrain the query to the last 2 years from now. You can omit `-i P2Y` or set it to `-i P2Y/2020-01-01` or maybe the year 3000
