### ISSUE TITLE
Joins query

### ISSUE THREAD

**Issue by lovenishgoyal** [implydata/plyql#46]
Hi Team,

We need path funnels via druid so we are looking for a option to run joins query on druid data. I checked that Join support is still in RoadMap. Could you please let me know Is it available?  
Looking forward to hear from you.

Thanks,
Lovenish

**Comment by vogievetsky** [comment]
Hi, joins are indeed on the roadmap but not available at this time. Will update this issue when they are.

There are a lot of people that I am aware of doing path funnels right now they are using custom druid queries that are specifically designed for the custom format of their data. 

What kind of query are you hoping to make? Could you provide an example please?

**Comment by davidagee** [comment]
Please note that this project is now deprecated. Please see the [Druid SQL docs](http://druid.incubator.apache.org/docs/latest/querying/sql) for information on using SQL syntax with Druid.
