### ISSUE TITLE
Write verbose output to stderr

### ISSUE THREAD

**Issue by gianm** [implydata/plyql#47]
This makes it possible to redirect the query results to a file while still seeing verbose output on the console, by doing:

```
plyql -h localhost:8082 -q 'select mystuff from mytable' -v > results
```

**Comment by vogievetsky** [comment]
oh wow, that is a very cool idea. I often wanted to do that myself. Is it common for tools to write non error things to stderr?

**Comment by gianm** [comment]
it's pretty common for tools where the output is machine-readable or something someone might want to save, since it makes it easier to feed that output into something else

**Comment by vogievetsky** [comment]
I love it when machines read my output 👍

**Comment by gianm** [comment]
😄
