### ISSUE TITLE
Support for range queries (Tableau)

### ISSUE THREAD

**Issue by kainoa21** [implydata/plyql#49]
Tableau tries to be "helpful" and rewrites some where predicates as range queries:

SELECT `mydatasource`.`country_iso_code` AS `country_iso_code`,
  SUM(`mydatasource`.`metric1`) AS `sum_metric1`
FROM `mydatasource`
WHERE ((`mydatasource`.`__time` >= TIMESTAMP('2016-02-01 00:00:00')) AND (`mydatasource`.`__time` <= TIMESTAMP('2016-03-31 23:59:59')) AND (((`mydatasource`.`country_iso_code` >= 'AD') AND (`mydatasource`.`country_iso_code` <= 'EC')) OR ((`mydatasource`.`country_iso_code` >= 'EG') AND (`mydatasource`.`country_iso_code` <= 'ZW'))))
GROUP BY 1

Message:
not supported IN rhs type SET/STRING_RANGE
Stack:
Error: not supported IN rhs type SET/STRING_RANGE

**Comment by vogievetsky** [comment]
This should be fixed in the latest plyql and in Imply 2.0.0
