### ISSUE TITLE
select timezone 

### ISSUE THREAD

**Issue by yxl040840219** [implydata/plyql#50]
hi, 
when i use http query the result :

wikipedia-query.json
{
    "queryType" : "groupBy",
     "dataSource" : "wikipedia",
     "intervals": [ "2016-07-29T00:00:00.000/2016-07-30T00:00:00.000" ],
     "granularity" : {"type": "period", "period": "PT1H", "timeZone": "Asia/Shanghai"},
     "aggregations" : [
       {
         "type" : "longSum",
         "name" : "delta",
        "fieldName" : "delta"
      }
    ]
 }

curl -X POST 'http://localhost:8082/druid/v2/?pretty' -H 'Content-Type:application/json' -d  @wikipedia-query.json
[ {
  "version" : "v1",
  "timestamp" : "2016-07-29T15:00:00.000+08:00",
  "event" : {
    "delta" : -499
  }
}, {
  "version" : "v1",
  "timestamp" : "2016-07-29T16:00:00.000+08:00",
  "event" : {
    "delta" : 187
  }
} ]

and use plyql query 
bin/plyql -h localhost -q "select sum(delta) from wikipedia  group by TIME_BUCKET(__time, PT1H, 'Asia/Shanghai')"

and the result 

[2016-07-29T07:00:00.000Z,2016-07-29T08:00:00.000Z) │ -499       │
│ [2016-07-29T08:00:00.000Z,2016-07-29T09:00:00.000Z) │ 187  |

 delta column is ok , but the timestamp is different  
  why ? something wrong with  Timezone ?

**Comment by vogievetsky** [comment]
The timestamp column is technically not different, just formatted differently.
This is related to #69. Closing this issue, watch #69
