### ISSUE TITLE
Consider using "nodejs" binary instead of "node"

### ISSUE THREAD

**Issue by sandwwraith** [implydata/plyql#55]
On Ubuntu and Debian, when you install node.js with npm, you get a binary called `nodejs`. Plyql uses binary named `node`, which requires installing `nodejs-legacy` package. Latter name is obsolete and should not be used, according to https://lists.debian.org/debian-devel-announce/2012/07/msg00002.html

**Comment by vogievetsky** [comment]
hmmm but it is `node` if installed on mac using homebrew. I wander what is the solution that works for everything. Thanks for the feedback!

**Comment by gianm** [comment]
That whole situation with `node` vs `nodejs` is amazing but also a mess (I read the thread for hours one afternoon and really regret it). Couple possible solutions:

- ship two wrappers, one with `node` and one with `nodejs`
- ship one wrapper that uses `/bin/sh` and is a shell script that detects which flavor of node is installed and then runs plyql with whatever it finds

**Comment by vogievetsky** [comment]
Hi, this should be fixed in `plyql@0.9.8` I have added a node looker upper https://github.com/implydata/plyql/blob/master/bin/plyql

Please confirm that it works without `nodejs-legacy` and reopen this if it does not.
