### ISSUE TITLE
plyql@0.8.15 use GROUP BY TIME_BUCKET can't get time info

### ISSUE THREAD

**Issue by fangyeqing** [implydata/plyql#61]
After update version@0.8.13 to @0.8.15 of the plyql module,
the following query to get data can't get time info:
GROUP BY TIME_BUCKET(__time,P1D,'Asia/Shanghai')

**Comment by vogievetsky** [comment]
Just ran `plyql -h dm -q "SELECT TIME_BUCKET(__time,P1D,'Asia/Shanghai') FROM wikipedia GROUP BY TIME_BUCKET(__time,P1D,'Asia/Shanghai') LIMIT 3"` and it appears to work. I think this might have been fixed at some point and is no longer a bug in the latest plyql or the plyql in Imply 2.0.0

Going to close the issue now, please reopen if you can still reproduce on plyql 0.9.x
