### ISSUE TITLE
Plyql gateway shutting down due to memory issues

### ISSUE THREAD

**Issue by rajitha703** [implydata/plyql#62]
Hi,

I brought up the mysql gateway pointing to a running druid instance. After firing few queries, the gateway crashes with following error  : 

    1: /* anonymous */(aka /* anonymous */) [/home/rajitha.r/local/node/lib/node_modules/plyql/build/plyql-mysql-gateway.js:~98] [pc=0x6d482f081f9] (this=0x1d9f1cd04381 <undefined>,row=0x25c40070c599 <an Object with map 0x23a11e18261>)
    2: arguments adaptor frame: 3->1
    3: map [native array.js:~994] [pc=0x6d482ed6e82] (this=0x75b9cf56fb9 <JS 
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

****************************
I googled a bit about this error and its advised to increase the parameter "--max-old-space-size" in node. I am not very sure about setting this variable. Can someone please help me fix this issue.

Thanks in advance,
Rajitha

**Comment by rajitha703** [comment]
Vadim's reply here helped fix the issue.

The plyql program that you run is actually just an executable node program with a hashbang you can always run it as `node <path-to>/plyql`
If you had plyql installed globally you can find it by running `which plyql` (on my system that returns: /usr/local/bin/plyql)
Now you can run `node --max-old-space-size=100m /usr/local/bin/plyql ...`

*******************************************************
Closing this one..

**Comment by talJoffeExelate** [comment]
Hi, I'm trying the exact same thing with plyql 0.10.7 and get the following error:

$ node --max-old-space-size=268435456 /usr/bin/plyql --host <broker-ip>:8080 --experimental-mysql-gateway 3306

/usr/lib/node_modules/plyql/bin/plyql:3
if command -v node > /dev/null 2>&1; then
   ^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)

I tried several variations on this and can't figure out what is the problem. any help is much appreciated
