### ISSUE TITLE
Could not resolve datasource

### ISSUE THREAD

**Issue by l15k4** [implydata/plyql#63]
Hey,

every request I submit to plyql serverl resolves in response : 

```
{"error":"could not resolve ${my-datasource}"}
```

even though `/druid/coordinator/v1/metadata/datasources` lists my 2 dataSources and `plyql` too : 

```
plyql -h foo:8082 -q 'SHOW TABLES'
│ COLUMNS      │
│ SCHEMATA     │
│ TABLES           │
│ gwiq-daily-p     │
│ gwiq-p              │
```

 I'm using plyql for about 5 months and it started after an upgrade to plyql `0.8.14` because I was unable to upgrade to `0.8.18` because of https://github.com/implydata/plyql/issues/60

Also it started after I added a new data source to druid. Any idea what could be wrong ?

However restarting `plyql` seems to be working, so I guess that `plyql` is doing some introspection at boot time and if it fails to do so, it will fail at query time afterwards...

**Comment by davidagee** [comment]
Please note that this project is now deprecated. Please see the [Druid SQL docs](http://druid.incubator.apache.org/docs/latest/querying/sql) for information on using SQL syntax with Druid.
