### ISSUE TITLE
Having and Orderby with Alias not working in Plyql

### ISSUE THREAD

**Issue by rajitha703** [implydata/plyql#65]
Hi All,

While select and group by work with aliases , notice that both Having and Order by in plyql queries fail as follows : 
## Order by :

mysql> select (user_summary_cube.**time), sum((user_summary_cube.adReq)) from usersummary user_summary_cube where (user_summary_cube.**time) between '2016-09-20 00:00:00' and '2016-09-23 00:00:00' group by (user_summary_cube.__time) order by (user_summary_cube.__time);
ERROR 1337 (_****): Something broke
## Having  : 

mysql>  select (user_summary_cube.**time), sum((user_summary_cube.adReq)) from usersummary user_summary_cube where (user_summary_cube.**time) between '2016-09-20 00:00:00' and '2016-09-23 00:00:00' group by (user_summary_cube.__time) having sum(user_summary_cube.adReq)>50;
ERROR 1337 (_****): Something broke

Only following query works : 
mysql> select (user_summary_cube.__time), sum((user_summary_cube.adReq)) from usersummary user_summary_cube where (user_summary_cube.__time) between '2016-09-20 00:00:00' and '2016-09-23 00:00:00' group by (user_summary_cube.__time) ;

Please help.

Regards
Rajitha

**Comment by davidagee** [comment]
Please note that this project is now deprecated. Please see the [Druid SQL docs](http://druid.incubator.apache.org/docs/latest/querying/sql) for information on using SQL syntax with Druid.
