### ISSUE TITLE
Issues with Sisense BI Tools

### ISSUE THREAD

**Issue by richiesgr** [implydata/plyql#68]
I'm trying to connect Sense Bi Tool to druid via the mysql drivers and I'm stuck at the start because the first query made by the tool to discovers the tables list is
SELECT DISTINCT `TABLE_NAME`, `TABLE_TYPE`, (TABLE_SCHEMA) AS `TABLE_SCHEMA` FROM INFORMATION_SCHEMA.TABLES WHERE `TABLE_SCHEMA` = N'plyql1'

perfectly working with MySQL of course. Please could you help me how to fix this in the code 
Thanks

**Comment by vogievetsky** [comment]
PlyQL can now parse `N'plyql1'` string literals. Try again with the newest version 0.9.14. Open new issue if something else fails. :-D
