### ISSUE TITLE
Case sensitivity during fetch tables via table_schema select

### ISSUE THREAD

**Issue by IL-87** [implydata/plyql#79]
**The problem:** I can't fetch tables via ODBC connection in Syncfusion dashboard platform.

The query which use Syncfusion to fetch tables:

`select table_schema, table_name FROM information_schema.tables where table_type = 'base table';`

The query which works:
`select table_schema, table_name FROM information_schema.tables where table_type = 'BASE TABLE';`

In standard MySQL this is not Case sensitive.
That makes sense because some of MySQL clients can't fetch the tables.

Thanks!

**Comment by davidagee** [comment]
Please note that this project is now deprecated. Please see the [Druid SQL docs](http://druid.incubator.apache.org/docs/latest/querying/sql) for information on using SQL syntax with Druid.
