### ISSUE TITLE
Use plyql in a programmatically way

### ISSUE THREAD

**Issue by lammoth** [implydata/plyql#8]
Maybe can be interesting adapt plyql to use it programmatically

**Comment by l15k4** [comment]
Yeah, we'd actually need to do some DSL on top of it. +1

**Comment by brettdh** [comment]
+1

Specifically, for plyql python bindings.

**Comment by vogievetsky** [comment]
Very happy to report that this is now possible. Python example coming soon.
http://imply.io/post/2016/05/04/programmatic-plyql.html

**Comment by lammoth** [comment]
Great Job!!, thank you!

**Comment by l15k4** [comment]
Awesome !!! :+1: 

Now it make sense to start plyql in `--json-server` mode on the broker nodes, right? As single SQL statement resolves into multiple Druid requests, it would be more effective if it was deployed on broker nodes.

**Comment by vogievetsky** [comment]
@l15k4 absolutely. The two places where plyql make sense is ether on the broker or on your computer

**Comment by l15k4** [comment]
@vogievetsky would you please consider creating a `status` endpoint for Health Checks? There is now hard to do that. 

I would use standard output for that but it is very verbose, it prints out each request and we currently have 40reqs/s which would produce huge amount of log files.

**Comment by vogievetsky** [comment]
@l15k4 just added `/health` to the [docs](https://github.com/implydata/plyql/blob/master/docs/json-over-http.md) and made sure there is a unit test for it
