### ISSUE TITLE
plyql mysql gateway will hang a request with not existed table

### ISSUE THREAD

**Issue by Tokkiu** [implydata/plyql#81]
We use the plyql mysql gateway on production env.
A bug occurs when we request the gateway.
We found that if the request select a table not existed, the gateway will hangs and the request be waiting for response forever.
I read the code and found the reason is that a promise has no catch so be rejected when error occurred.
I fixed the bug in my merge request #80 .

**Comment by davidagee** [comment]
Please note that this project is now deprecated. Please see the [Druid SQL docs](http://druid.incubator.apache.org/docs/latest/querying/sql) for information on using SQL syntax with Druid.
