### ISSUE TITLE
plyql mysql gateway  throw an error when I used measure as filter

### ISSUE THREAD

**Issue by SJYeon** [implydata/plyql#87]
SELECT sum(count) FROM pull_down_refresh WHERE __time>= '2019-01-18T04:00:00' and has_interval = 1;
has_interval is a measure. 

**(node:195408) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: can not convert $has_interval:NUMBER = 1 to filter because it references an un-filterable metric 'has_interval' which is most likely rolled up.**

How do I use a measure to filter ？

**Comment by gianm** [comment]
Hey @SJYeon, you might prefer using Druid SQL: http://druid.io/docs/latest/querying/sql. PlyQL is no longer being maintained, since Druid SQL meets the same needs.

**Comment by davidagee** [comment]
Please note that this project is now deprecated. Please see the [Druid SQL docs](http://druid.incubator.apache.org/docs/latest/querying/sql) for information on using SQL syntax with Druid.
