### ISSUE TITLE
Add support for hllsketch aggregates

### ISSUE THREAD

**Issue by jordan-young-vt** [implydata/plyql#88]
I think we should add support for a --force-hll option similar to the --force-theta option.  It looks like newer versions of plywood have built some support for this (>=0.20.8).

**Comment by davidagee** [comment]
Please note that this project is now deprecated. Please see the [Druid SQL docs](http://druid.incubator.apache.org/docs/latest/querying/sql) for information on using SQL syntax with Druid.
